export default {
    materials: [{
        id: 5399,
        name: '猪'
    }, {
        id: 104,
        name: '鸡'
    }, {
        id: 5443,
        name: '牛'
    }, {
        id: 5418,
        name: '羊'
    }, {
        id: 275,
        name: '鸭'
    }, {
        id: 605,
        name: '牛蛙'
    }, {
        id: 719,
        name: '兔肉'
    }, {
        id: 20132,
        name: '饭'
    }, {
        id: 20133,
        name: '面'
    }, {
        id: 20148,
        name: '饺子'
    }, {
        id: 20150,
        name: '混沌'
    }, {
        id: 957,
        name: '鱼'
    }, {
        id: 4553,
        name: '贝'
    }, {
        id: 469,
        name: '虾'
    }, {
        id: 1183,
        name: '螃蟹'
    }],

    taste: [{
        id: 51359,
        name: '辣'
    }, {
        id: 51922,
        name: '咖喱'
    }, {
        id: 40066,
        name: '糖醋'
    }, {
        id: 52413,
        name: '蒜香'
    }, {
        id: 51449,
        name: '酸甜'
    }, {
        id: 52407,
        name: '奶香'
    }, {
        id: 52401,
        name: '孜然'
    }, {
        id: 51875,
        name: '鱼香'
    }, {
        id: 52399,
        name: '五香'
    }, {
        id: 51460,
        name: '清淡'
    }]
}